@baseurl = http://localhost:3000

GET {{baseurl}}/users HTTP/1.1

###
GET {{baseurl}}/users/c00af9cb-20e2-409c-979b-166eb7dd705d HTTP/1.1

###
POST {{baseurl}}/users HTTP/1.1
content-type: application/json

{
  "name": "John Smith",
  "email": "john.smith@gmail.com",
  "password": "secret"
}

###
POST {{baseurl}}/tasks HTTP/1.1
content-type: application/json
x-user-id: c00af9cb-20e2-409c-979b-166eb7dd705d

{
  "title": "code the API"
}